apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Homelab

    background:
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 100 # 0-100

    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Hypervisor:
        header: true
        style: row
        columns: 4
      Services:
        header: true
        style: row
        columns: 2
      DNS:
        header: true
        style: row
        columns: 1
      Network:
        header: true
        style: row
        columns: 3
      Storage:
        header: true
        style: row
        columns: 1
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Hypervisor:
        - Proxmox:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_GIANT_URL}}"
            description: pve1
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_GIANT_URL}}"
                username: "{{HOMEPAGE_VAR_GIANT_USER}}"
                password: "{{HOMEPAGE_VAR_GIANT_PASS}}"
        - Proxmox:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_COMET_URL}}"
            description: pve2
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_COMET_URL}}"
                username: "{{HOMEPAGE_VAR_COMET_USER}}"
                password: "{{HOMEPAGE_VAR_COMET_PASS}}"
        - Proxmox:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_MUTINY_URL}}"
            description: pve3
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_MUTINY_URL}}"
                username: "{{HOMEPAGE_VAR_MUTINY_USER}}"
                password: "{{HOMEPAGE_VAR_MUTINY_PASS}}"
        - PBS:
            icon: proxmoxbackupserver.svg
            href: "{{HOMEPAGE_VAR_PBS_URL}}"
            description: pbs
    - Services:
        - Grafana:
            icon: grafana.svg
            href: "{{HOMEPAGE_VAR_GRAFANA_URL}}"
            description: dashboard
        - Calibre:
            icon: calibreweb.svg
            href: "{{HOMEPAGE_VAR_CALIBRE_URL}}"
            description: books
    - DNS:
        - Pi-Hole1:
            icon: pi-hole.svg
            href: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}"
            description: dns
            widget:
                type: pihole
                url: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}"
                version: 6
                key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_1}}"
    - Network:
        - Router:
            icon: router.svg
            href: "{{HOMEPAGE_VAR_ROUTER_URL}}"
            description: network
        - Switch:
            href: "{{HOMEPAGE_VAR_SWITCH_URL}}"
            description: network
        - Uptime Kuma:
            icon: uptime-kuma.svg
            href: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
            description: ping
    - Storage:
        - MooseFS:
            icon: storage.svg
            href: "{{HOMEPAGE_VAR_MOOSEFS_URL}}"
            description: storage
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /

    - datetime:
        text_size: xl
        format:
          timeStyle: short
  docker.yaml: ""
