apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gatus-monitor
  namespace: monitoring-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: gatus
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
