apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
    namespace: auth
type: Opaque
stringData:
    encryption-key: ENC[AES256_GCM,data:S4xQ2PzfritSumQZPzr7d+MViE17Vuxy+JRJOry1YX7GjQzLDe5ywWbo23ewyjRVwPf08cFFAptvA16n3mdR6g==,iv:NdzM8OO5DOmgvyM93blNFzqs+wyhx/dRlNMwlxe1qxM=,tag:gVnE8M+K/PEiyp5KAbZobA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUK0NzR2M5b0Y5Ri9EWk5o
            YnBkVTJFNlFUY294bmU2RnVwK0FQV2w0YlVBCk5HNWE5eSs5S283Z0V2Wmp2Y2U1
            SDBNOUFtRnIvSXE0VXpSc1MyN3gvRkkKLS0tIE1sZUdBazl2Z25yU1pQOHFBcjlw
            c3VVMXJxV3EwL1g5MmRDSy9iM2FrL1EKy0VdOC6+vz4jdSbv2DyFdXjSE6tXl5gM
            sXLsumlzbsPRWkpqx5UtazWsS97EnZh+SMqU74F8p2ioY/EchkawoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kr4f2n0has5ydamjwyev9xejm6s58ju5dqxc0qvh0yed2uvsu8qhj7nql
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T06:51:00Z"
    mac: ENC[AES256_GCM,data:1LDlMDAioSHh3kEwtThnwH/CBO6wg2CmWScwBEYUb/KzQF8+OvVOQdIRPDtHau+ziOx/EjYUoy18t673zXA1c4a5MBS/Y1lEgl2uz5EN/cCTREzFIOv/xs31YdnqdZLt7krrueUhpdGHJMpwP6nrS8SNMMqzcDEtfr5j9uQ2Ndo=,iv:updaG6VohPF6vXUPCzcnnbdr4G21IiRtle++qHgPMGs=,tag:7NMuv9xO2iBviS7/KtQT9A==,type:str]
    version: 3.13.1
