set skip on lo

##########
# macros #
##########
wireguard_peers = "{}"
tcp_services = "{ https, http, www }"
udp_services = "{ domain, ntp }"
minefield="1024:9999"
unused_ports = "{ 23, 22, 137, 139, 445 }"
ssh_alternate_port=2222
all_ports = "{ 2222, 23, 22, 137, 139, 445, 1024:9999 }"

##########
# tables #
##########
table <bruteforce> persist

################
# common rules #
################
block all
#block quick proto tcp from <bruteforce> to (egress) port $all_ports
block quick proto tcp from <bruteforce> \
  to (egress) port $all_ports

pass quick proto tcp to port $tcp_services \
	keep state (max-src-conn 100, max-src-conn-rate 100/1)

pass quick proto { udp tcp } to port $udp_services \
	keep state (max-src-conn 100, max-src-conn-rate 100/1)

pass proto tcp from any to (egress) \
  port $ssh_alternate_port \
  synproxy state \
  (max-src-conn 3, max-src-conn-rate 3/10, \
  overload <bruteforce> flush global \
  )

pass in proto tcp from any to (egress) port $ssh_alternate_port

pass inet proto icmp

pass on egress proto udp from $wireguard_peers to any port 4433
