include: "/etc/unbound/conf.d/*.conf"

server:
	module-config: "validator iterator"
	username: ""
	chroot: ""
	port: 5355
	do-daemonize: yes
    	# run unbound-anchor -a "/var/unbound/etc/root.key" to generate
    	auto-trust-anchor-file: "/var/unbound/etc/root.key"
