# =============== top level system-upgrade ks ===============
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-upgrade
resources:
  - crd.yaml
  - system-upgrade-controller.yaml
  - plan.yaml
