apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
      version: 0.15.3
  interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
  valuesFrom:
    - kind: ConfigMap
      name: metallb-values
      valuesKey: values.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-values
  namespace: metallb-system
data:
  values.yaml: |
    speaker:
      ignoreExcludeLB: true
      frr:
        enabled: false
