apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoriametrics
  namespace: logging-system
spec:
  interval: 60m0s
  url: https://victoriametrics.github.io/helm-charts/
