-- listen on 0.0.0.0
addLocal("0.0.0.0:53")

-- local unbound instance
newServer("127.0.0.1:5355")

-- acl IPs
addACL('217.217.243.71')

setServerPolicy(firstAvailable)

-- caching
pc = newPacketCache(10000, {maxTTL=86400, minTTL=0, temporaryFailureTTL=60, staleTTL=60, dontAge=false})
getPool(""):setCache(pc)
