# =============== top level nfs ks ===============
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ../../../comet/storage/nfs/release.yaml
  - ../../../comet/storage/nfs/storageclass.yaml

commonLabels:
  app.kubernetes.io/name: nfs-csi

patches:
  - target:
      group: storage.k8s.io
      version: v1
      kind: StorageClass
      name: nfs-csi
    patch: |-
      - op: replace
        path: /parameters/server
        value: 100.64.0.3
