apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: deny-metrics
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: gatus-route
  authorization:
    defaultAction: Allow
    rules:
      - name: deny-metrics
        action: Deny
        operation:
          path:
            type: PathPrefix
            value: /metrics
