# =============== top level envoy-gateway ks ===============
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system

resources:
  - ../../comet/envoy-gateway/namespace.yaml
  - ../../comet/envoy-gateway/release.yaml
  - ../../comet/envoy-gateway/gatewayclass.yaml
  - ../../comet/envoy-gateway/gateway.yaml
  - ../../comet/envoy-gateway/clienttrafficpolicy.yaml
  - ../../comet/envoy-gateway/envoyproxy.yaml

patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: envoy-gateway
    patch: |-
      - op: add
        path: /spec/addresses
        value:
          - type: IPAddress
            value: "100.64.0.1"
          - type: IPAddress
            value: "100.64.0.2"
