# =============== top level envoy-gateway ks ===============
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system

resources:
  - ../../comet/envoy-gateway/namespace.yaml
  - ../../comet/envoy-gateway/release.yaml
  - ../../comet/envoy-gateway/gatewayclass.yaml
  - ../../comet/envoy-gateway/gateway.yaml
  - ../../comet/envoy-gateway/clienttrafficpolicy.yaml
  - ./routes
