apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vlstorage
  namespace: logging-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-csi
