# =============== top level gatus ks ===============
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ../../../comet/monitoring/gatus/deployment.yaml
  - ../../../comet/monitoring/gatus/service.yaml
  - ../../../comet/monitoring/gatus/config.yaml
  - ../../../comet/monitoring/gatus/sa.yaml
  - ../../../comet/monitoring/gatus/namespace.yaml
  - ../../../../netpols/deny-by-default-ingress.yaml
  - ../../../../netpols/allow-envoy-ingress.yaml
  - ../../../comet/monitoring/gatus/allow-dns-gatus.yaml
  - ../../../comet/monitoring/gatus/allow-egress-internet.yaml
  - ../../../comet/monitoring/gatus/routes

components:
  - ../../../../shared/components/gvisor

patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: gatus-route
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "gatus.ext4.xyz"
