apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: moosefs-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
  labels:
    app: calibre
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      containers:
        - name: calibre
          image: lscr.io/linuxserver/calibre-web:latest
          ports:
            - containerPort: 8083
          volumeMounts:
            - mountPath: /library/books/
              name: homepage-books
            - mountPath: /library/config/
              name: homepage-config
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: homepage-books
          persistentVolumeClaim:
            claimName: calibre
        - name: homepage-config
          persistentVolumeClaim:
            claimName: calibre
---
apiVersion: v1
kind: Service
metadata:
  name: calibre
spec:
  type: ClusterIP
  selector:
    app: calibre
  ports:
    - port: 80
      targetPort: 8083
