apiVersion: v1
kind: Secret
metadata:
    name: aio-env
    namespace: external-apps
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:SlIapKd5cE1wY3MJwA6dQSJ5lho6zmYuRTirLa1j9SGcsPjYSqiwTmkExXFLjdV+CRJbd2fS8DnBOOH1SQTykQ==,iv:akebSb54RUDpOuo7oziTvcK8V4I/5UazAvZ8kDB7icQ=,tag:P/sNhBk4Ks6BGOPEtudWrQ==,type:str]
    AIOSTREAMS_AUTH: ENC[AES256_GCM,data:VPcdbwjkj6/r/0TE02ZYByUOHIIQ8o1f+fyU7NU4xRmQ3OEYuBM=,iv:pFZkKI4B9vsl0VsPF2dagGblGaH5aC49e6LndhaK7qA=,tag:M4ODEN/8xSleRgT3P+BnAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU0t4OFVjdzhXcE5Gb1RV
            UDNSVHNYQXl1bVkvcmd2R0YzaC83N3RSUGtrCmxmd0kvelFubWcyTElkb1ZGMGw1
            YTNNNUJEeWxnYnZQTTJzcVZ2WU83QlUKLS0tIFBhL1FVMHJJQVB1emZpdG8rV0Q3
            N1llZHp6MVYyOVJRMDdLaG96ZnZMWmcKxLFUxBN/l3S0RURP1OxZFNKSMTWYcr/c
            2czsCIsTH0GyWRKe1XMZjYpJ/5a4tl1tGVDhnjcdCnGThLbb0b/kXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kr4f2n0has5ydamjwyev9xejm6s58ju5dqxc0qvh0yed2uvsu8qhj7nql
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T07:11:35Z"
    mac: ENC[AES256_GCM,data:Sc2uagzr1OLEi8a7IZIJL8Z/YcCqSFYm9jAmvVGYD5ceu9pI4qKjzGUdgM7CXvPHJPPnquTGP1H8gkrfkIy/Ek3k2STp479NwIh4eUHIcnvUW21uAFcK+hTBPGYrB0osyDldKl9rW8fHjiL384cSli0F98o84vhQUVa8p5i/lCI=,iv:dqPB1mjG5uzs95jBiOa2yTNJACk7ZoEtr3Se1RkW+kY=,tag:5XcHyqVVpl6xn8pvISN3Bg==,type:str]
    version: 3.13.1
