# =============== top level monitoring-system ks ===============
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-system

resources:
  - release.yaml
  - namespace.yaml
  - ./routes

configMapGenerator:
  - name: monitoring-grafana-dashboards
    files:
      - ./dashboards/k8s-views-global.json
      - ./dashboards/k8s-views-nodes.json
      - ./dashboards/k8s-views-pods.json
    options:
      labels:
        grafana_dashboard: "1"

