apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gatus-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "gatus.ext4.xyz"
  rules:
    - backendRefs:
        - name: gatus
          port: 8080
