apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: vl-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: vl-route
  oidc:
    provider:
      issuer: "https://id.ext4.xyz"
    clientID: "35ea1a5d-6d91-4618-851b-727cc910f887"
    clientSecret:
      name: pocket-oidc
    redirectURL: "https://logs.ext4.xyz/oauth2/callback"
    logoutPath: "/logout"
