apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: kube-system
      # renovate: datasource=helm depName=cilium registryUrl=https://helm.cilium.io/
      version: 1.19.5
  interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
      valuesKey: values.yaml
